# Generated by Django 5.1.3 on 2024-11-13 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelos_usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelousuariomodel',
            name='tipo_prompt',
            field=models.CharField(default=''),
            preserve_default=False,
        ),
    ]
